# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.CharField(max_length=256)),
                ('qualification', models.CharField(max_length=25)),
                ('completion_year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)])),
                ('qualification_type', models.CharField(default='highest', max_length=25)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_education',
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('any_active_loans', models.BooleanField(default=False)),
                ('any_owned_vehicles', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Other', 'Other')], default='Other', max_length=50)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Other', 'Other')], default='Other', max_length=50)),
                ('dependents', models.IntegerField(default=0)),
                ('phone_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_finance',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('office_city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('is_phone_no_verified', models.BooleanField(default=False)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
                ('total_experience', models.IntegerField(default=0)),
                ('nature_of_work', models.CharField(choices=[('Self Employed', 'Self Employed'), ('Salaried', 'Salaried'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], default='Other', max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('organisation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.OrganisationType')),
                ('profession_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ProfessionType')),
                ('salary_payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SalaryPaymentMode')),
            ],
            options={
                'db_table': 'customer_profession',
            },
        ),
        migrations.CreateModel(
            name='Vahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_no', models.CharField(max_length=50)),
                ('make', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('make_model', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fuel', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('display_variant', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('short_variant', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('vehicle_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('vertical', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rto_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rto_lnt_location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rto_plate_lnt_location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('registration_date', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_vahan',
            },
        ),
    ]
