# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_1', models.FileField(upload_to=documents.models.content_file_name)),
                ('document_2', models.FileField(blank=True, null=True, upload_to=documents.models.content_file_name)),
                ('document_3', models.FileField(blank=True, null=True, upload_to=documents.models.content_file_name)),
                ('document_4', models.FileField(blank=True, null=True, upload_to=documents.models.content_file_name)),
                ('document_5', models.FileField(blank=True, null=True, upload_to=documents.models.content_file_name)),
                ('document_6', models.FileField(blank=True, null=True, upload_to=documents.models.content_file_name)),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('verified', 'verified')], default='uploaded', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('usage', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
            options={
                'db_table': 'customer_document_types',
            },
        ),
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType'),
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together=set([('customer', 'document_type')]),
        ),
    ]
