# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
        ('common', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('manufacturing_year', models.CharField(max_length=256)),
                ('approximate_price', models.IntegerField()),
                ('down_payment', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'bike_loan',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installment_number', models.IntegerField()),
                ('expected_installment_amount', models.IntegerField()),
                ('expected_repayment_date', models.DateTimeField()),
                ('actual_installment_amount', models.IntegerField(blank=True, null=True)),
                ('actual_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('penalty_amount', models.IntegerField(blank=True, null=True)),
                ('installment_paid', models.BooleanField(default=False)),
                ('installment_interest_part', models.IntegerField()),
                ('installment_principal_part', models.IntegerField()),
            ],
            options={
                'db_table': 'installment',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loan_amount_applied', models.IntegerField()),
                ('processing_fee', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('interest_rate_per_tenure', models.DecimalField(decimal_places=4, max_digits=6)),
                ('penalty_rate_per_tenure', models.DecimalField(decimal_places=4, max_digits=6)),
                ('status', models.CharField(choices=[('pre_process', 'pre_process'), ('processing', 'processing'), ('rejected', 'rejected'), ('disbursed', 'disbursed'), ('completly_paid', 'completly_paid'), ('partially_paid', 'partially_paid')], default='pre_process', max_length=50)),
                ('application_datetime', models.DateTimeField(blank=True, null=True)),
                ('disbursal_datetime', models.DateTimeField(blank=True, null=True)),
                ('security', models.CharField(default='PDC', max_length=200)),
                ('margin', models.IntegerField(blank=True, default=0, null=True)),
                ('is_interest_deducted_at_source', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.Lender')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loan_amount', models.IntegerField(default=0)),
                ('monthly_income', models.IntegerField(default=0)),
                ('existing_emi', models.IntegerField(default=0)),
                ('loan_tenure', models.IntegerField(default=0)),
                ('loan_emi', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('loan_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.LoanPurpose')),
            ],
            options={
                'db_table': 'loan_product',
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_product.Loan'),
        ),
        migrations.AlterUniqueTogether(
            name='loanproduct',
            unique_together=set([('customer', 'id')]),
        ),
    ]
