# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('present_state', models.CharField(choices=[(b'unknown', b'unknown'), (b'sign_up', b'sign_up'), (b'loan_product_submit', b'loan_product_submit'), (b'pan_submit', b'pan_submit'), (b'professional_submit', b'professional_submit'), (b'finance_submit_email_unverified', b'finance_submit_email_unverified'), (b'education_submit', b'education_submit'), (b'finance_submit_email_verified', b'finance_submit_email_verified'), (b'eligibility_submit', b'eligibility_submit'), (b'aadhaar_submit', b'aadhaar_submit'), (b'aadhaar_detail_submit', b'aadhaar_detail_submit'), (b'bank_detail_submit', b'bank_detail_submit'), (b'personal_contact_submit', b'personal_contact_submit'), (b'document_submit_email_unverified', b'document_submit_email_unverified'), (b'document_submit_email_verified', b'document_submit_email_verified'), (b'kyc_submit', b'kyc_submit'), (b'eligibility_rejected_kyc_submit', b'eligibility_rejected_kyc_submit'), (b'eligibility_approved_kyc_proccessing', b'eligibility_approved_kyc_proccessing'), (b'eligibility_approved_kyc_rejected', b'eligibility_approved_kyc_rejected'), (b'eligibility_approved_kyc_approved', b'eligibility_approved_kyc_approved'), (b'loan_specification_reviewed', b'loan_specification_reviewed'), (b'loan_submit_aggrement_unsigned', b'loan_submit_aggrement_unsigned'), (b'aggrement_signed_loan_application_proccessing', b'aggrement_signed_loan_application_proccessing'), (b'loan_application_proccessed', b'loan_application_proccessed'), (b'loan_application_errored', b'loan_application_errored')], default=b'sign_up', max_length=100)),
                ('from_state', models.CharField(choices=[(b'unknown', b'unknown'), (b'sign_up', b'sign_up'), (b'loan_product_submit', b'loan_product_submit'), (b'pan_submit', b'pan_submit'), (b'professional_submit', b'professional_submit'), (b'finance_submit_email_unverified', b'finance_submit_email_unverified'), (b'education_submit', b'education_submit'), (b'finance_submit_email_verified', b'finance_submit_email_verified'), (b'eligibility_submit', b'eligibility_submit'), (b'aadhaar_submit', b'aadhaar_submit'), (b'aadhaar_detail_submit', b'aadhaar_detail_submit'), (b'bank_detail_submit', b'bank_detail_submit'), (b'personal_contact_submit', b'personal_contact_submit'), (b'document_submit_email_unverified', b'document_submit_email_unverified'), (b'document_submit_email_verified', b'document_submit_email_verified'), (b'kyc_submit', b'kyc_submit'), (b'eligibility_rejected_kyc_submit', b'eligibility_rejected_kyc_submit'), (b'eligibility_approved_kyc_proccessing', b'eligibility_approved_kyc_proccessing'), (b'eligibility_approved_kyc_rejected', b'eligibility_approved_kyc_rejected'), (b'eligibility_approved_kyc_approved', b'eligibility_approved_kyc_approved'), (b'loan_specification_reviewed', b'loan_specification_reviewed'), (b'loan_submit_aggrement_unsigned', b'loan_submit_aggrement_unsigned'), (b'aggrement_signed_loan_application_proccessing', b'aggrement_signed_loan_application_proccessing'), (b'loan_application_proccessed', b'loan_application_proccessed'), (b'loan_application_errored', b'loan_application_errored')], default=b'unknown', max_length=100)),
                ('to_state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_state',
            },
        ),
    ]
