# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('branch_detail', models.CharField(max_length=256)),
                ('ifsc', models.CharField(max_length=20)),
                ('upi_mobile_number', models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '9999999999'. 10 digits allowed.", regex='^$|\\d{10}$')])),
                ('is_upi_mobile_number_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer_bank_details',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('alternate_email_id', models.EmailField(max_length=254)),
                ('is_alternate_email_id_verified', models.BooleanField(default=False)),
                ('alternate_mob_no', models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '9999999999'. 10 digits allowed.", regex='^$|\\d{10}$')])),
                ('is_alternate_mob_no_verified', models.BooleanField(default=False)),
                ('current_address_line1', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('current_address_line2', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('current_city', models.CharField(blank=True, max_length=25, null=True)),
                ('current_state', models.CharField(blank=True, max_length=25, null=True)),
                ('current_pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message="Pincode must be entered in format: '123456'. 6 Characters allowed.", regex='^[1-9][0-9]{5}$')])),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
