# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pan', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="PAN must be entered in the format: 'ABCDE1234F'. 10 Characters allowed.", regex='[a-zA-Z]{5}\\d{4}[a-zA-Z]{1}')])),
                ('is_verified', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('first_name', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('middle_name', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('last_name', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('father_first_name', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('father_middle_name', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('father_last_name', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Data must be entered in Alphabets only.', regex='$|[a-zA-Z]+')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=25)),
                ('pan_updates', models.IntegerField(blank=True, default=1)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_pan',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pan',
            unique_together=set([('customer', 'id')]),
        ),
    ]
