# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('max_current_loans_allowed', models.IntegerField(default=1)),
                ('credit_limit', models.IntegerField()),
                ('number_of_active_loans', models.IntegerField(default=0)),
                ('number_of_repaid_loans', models.IntegerField(default=0)),
                ('total_current_debt', models.IntegerField(default=0)),
                ('eligible_for_loan', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'borrower',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lender_type', models.CharField(choices=[('nbfc', 'NBFC'), ('bank', 'Bank')], default='nbfc', max_length=50)),
                ('allocation_limit', models.IntegerField(default=10000000)),
            ],
            options={
                'db_table': 'lender',
            },
        ),
    ]
