# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('customer_alternate_email', 'customer_alternate_email'), ('customer_profession_email', 'customer_profession_email')], default='customer_alternate_email', max_length=50)),
                ('verification_code', models.CharField(blank=True, default=messenger.models.random_code32, max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('times', models.IntegerField(blank=True, default=1, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'email_verification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message_title', models.TextField(blank=True, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('data_message', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[(b'unknown', b'unknown'), (b'sign_up', b'sign_up'), (b'loan_product_submit', b'loan_product_submit'), (b'pan_submit', b'pan_submit'), (b'professional_submit', b'professional_submit'), (b'finance_submit_email_unverified', b'finance_submit_email_unverified'), (b'education_submit', b'education_submit'), (b'finance_submit_email_verified', b'finance_submit_email_verified'), (b'eligibility_submit', b'eligibility_submit'), (b'aadhaar_submit', b'aadhaar_submit'), (b'aadhaar_detail_submit', b'aadhaar_detail_submit'), (b'bank_detail_submit', b'bank_detail_submit'), (b'personal_contact_submit', b'personal_contact_submit'), (b'document_submit_email_unverified', b'document_submit_email_unverified'), (b'document_submit_email_verified', b'document_submit_email_verified'), (b'kyc_submit', b'kyc_submit'), (b'eligibility_rejected_kyc_submit', b'eligibility_rejected_kyc_submit'), (b'eligibility_approved_kyc_proccessing', b'eligibility_approved_kyc_proccessing'), (b'eligibility_approved_kyc_rejected', b'eligibility_approved_kyc_rejected'), (b'eligibility_approved_kyc_approved', b'eligibility_approved_kyc_approved'), (b'loan_specification_reviewed', b'loan_specification_reviewed'), (b'loan_submit_aggrement_unsigned', b'loan_submit_aggrement_unsigned'), (b'aggrement_signed_loan_application_proccessing', b'aggrement_signed_loan_application_proccessing'), (b'loan_application_proccessed', b'loan_application_proccessed'), (b'loan_application_errored', b'loan_application_errored')], default=b'unknown', max_length=50)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '9999999999'. 10 digits allowed.", regex='^$|\\d{10}$')])),
                ('otp_code', models.CharField(blank=True, max_length=12)),
                ('times', models.IntegerField(blank=True, default=1, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'otp_verification',
            },
        ),
        migrations.CreateModel(
            name='PreSignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('app_registration_id', models.TextField(blank=True, unique=True)),
                ('imei', models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Data must be entered in Digits only.', regex='[0-9]+')])),
            ],
            options={
                'db_table': 'pre_signup_data',
            },
        ),
    ]
