# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
        ('loan_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Initiated', max_length=50)),
                ('transaction_type', models.CharField(choices=[('Loan Availed', 'Loan Availed'), ('EMI Paid', 'EMI Paid'), ('Penalty Paid', 'Penalty Paid'), ('Past EMI and Penalty Paid', 'Past EMI and Penalty Paid'), ('Current EMI, Past EMI and Penalty Paid', 'Current EMI, Past EMI and Penalty Paid'), ('Processing Fees Paid', 'Processing Fees Paid')], default='Loan Availed', max_length=50)),
                ('status_actor', models.CharField(choices=[('nbfc', 'NBFC'), ('upwards', 'Upwards')], default='upwards', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.Borrower', to_field='customer')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan_product.Installment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_product.Loan')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
