CREDENTIALS_FILE = 'analytics/v1/services/algo360_credentials.json'

MAB_VARIABLES = ['monthly_average_balance_lifetime', 'monthly_average_balance_12',
                 'monthly_average_balance_6', 'monthly_average_balance_3', 'monthly_average_balance_1']
SALARY_VARIABLE = 'salary'

ALGO360_UPWARDS_MAPPING = {
    'var201093': 'monthly_average_balance_lifetime',
    'var201094': 'monthly_average_balance_12',
    'var201095': 'monthly_average_balance_6',
    'var201096': 'monthly_average_balance_3',
    'var201097': 'monthly_average_balance_1',
    'var201204': 'number_of_cheque_bounce_1',
    'var201203': 'number_of_cheque_bounce_3',
    'var202003': 'is_credit_card_overlimited',
    'var202064': 'credit_card_last_payment_due',
    'var101003': 'salary',
}

CREDIT_REPORT_MAPPING = {
    'Loan Product': {
        'fields': {
            'monthly_income': 'Monthly Income Specified On Loan Specification Screen (Rs)',
            'existing_emi': 'Any Existing Emis  (Rs)',
            'loan_purpose__name': 'Purpose Of The Loan',
            'loan_amount': 'Loan Amount (Rs)',
        },
        'model_class': 'loan_product.models.LoanProduct',
    },
    'Bike Loan': {
        'fields': {
            'brand': 'Brand Of The Bike',
            'model': 'Model Of The Bike',
            'manufacturing_year': 'Manufacturing Year Of The Bike',
            'approximate_price': 'Approximate Price Of The Bike (Rs)',
            'down_payment': 'Down Payment Of The Bike (Rs)',
        },
        'model_class': 'loan_product.models.BikeLoan',
    },
    'PAN': {
        'fields': {
            'status': 'Pan Status Of The Customer',
            'title': 'Title Of The Customer In Pan',
            'first_name': 'First Name Of The Customer In Pan',
            'middle_name': 'First Name Of The Customer In Pan',
            'last_name': 'Last Name Of The Customer In Pan',
            'dob': 'Date Of Birth Of The Customer In Pan',
            'pan_updates': 'Pan Updates Of The Customer',
        },
        'model_class': 'pan.models.Pan',
    },
    'Profession': {
        'fields': {
            'company': 'Name Of The Company, Where Customer Works',
            'organisation_type__name': 'Organisation Type Of The Company, Where Customer Works',
            'salary_payment_mode__name': 'Salary Payment Mode Of The Customer',
            'profession_type__type_name': 'Profession Type Of The Customer',
            'email': 'Professional Email Of The Customer',
            'is_email_verified': 'Is Professional Email Of The Customer Verified?',
            'department': "Company'S Department Where Customer Works",
            'office_city': 'City Where Customer Works',
            'salary': 'Monthly Salary Of The Customer (Rs)',
            'total_experience': 'Total Work Experience Of The Customer In Months',
            'nature_of_work': 'Nature Of Work Of The Customer',
        },
        'model_class': 'eligibility.models.Profession',
    },
    'Education': {
        'fields': {
            'college': 'Last College Attended By Customer',
            'qualification': 'Highest Qualification Of The Customer',
            'completion_year': 'Highest Qualification Completion Year Of The Customer',
        },
        'model_class': 'eligibility.models.Education',
    },
    'Finance': {
        'fields': {
            'any_active_loans': 'Any Active Loans Taken By The Customer',
            'any_owned_vehicles': 'Any Vehicle Owned By The Customer',
            'marital_status': 'Maritial Status Of The Customer',
            'dependents': 'Number Of Dependents On Customer',
        },
        'model_class': 'eligibility.models.Finance',
    },
    'SMS Scraping': {
        'fields':     {
            'monthly_average_balance_lifetime': 'Monthly Average Balance Of The Customer In His Lifetime (Rs)',
            'monthly_average_balance_12': 'Monthly Average Balance Of The Customer In In Last 12 Months (Rs)',
            'monthly_average_balance_6': 'Monthly Average Balance Of The Customer In Last 6 Months (Rs)',
            'monthly_average_balance_3': 'Monthly Average Balance Of The Customer In Last 3 Months (Rs)',
            'monthly_average_balance_1': 'Monthly Average Balance Of The Customer In Last 1 Months (Rs)',
            'number_of_cheque_bounce_1': 'Number Of Cheque Bounced In Last Month',
            'number_of_cheque_bounce_3': 'Number Of Cheque Bounced In Last 3 Month',
            'salary': 'Salary Deduced From Sms Data  (Rs)',
        },
        'model_class': 'analytics.models.Algo360',
    },
}

CREDIT_REPORT_VARIABLE_NAME_MAP = {
    'SMS Scraping': {
        'var206002': 'Flag - Missed Loan Payments/ EMIs',
        'var206003': 'Number Of Loan Accounts Lifetime',
        'var206004': 'Number Of Loan Accounts Last 12 Months',
        'var206005': 'Number Of Loan Accounts Last 6 Months',
        'var206006': 'Number Of Loan Accounts Last 3 Months',
        'var206007': 'Number Of Loan Accounts Last 1 Month',
        'var206008': 'Number Of Loan Accounts Last 3 Months By Number Of Loan Accounts Last 6 Months',
        'var206009': 'Avg. Monthly Loan Liability Lifetime (Rs)',
        'var206010': 'Avg. Monthly Loan Liability Last 12 Months (Rs)',
        'var206011': 'Avg. Monthly Loan Liability Last 6 Months (Rs)',
        'var206012': 'Avg. Monthly Loan Liability Last 3 Months  (Rs)',
        'var206013': 'Avg. Monthly Loan Liability Last 1 Month (Rs)',
        'var206020': 'Number Of Loan Payments Missed Lifetime',
        'var206021': 'Number Of Loan Payments Missed Last 12 Months',
        'var206022': 'Number Of Loan Payments Missed Last 6 Months',
        'var206023': 'Number Of Loan Payments Missed Last 3 Months',
        'var206024': 'Number Of Loan Payments Missed Last 1 Month',
        'var206036': 'Sender Name in Loans',
        'var206037': 'Loan Account Number',
        'var101001': 'Lifetime Available (In Months) / Data Available For Duration',
        'var201001': 'Number Of CASA Accounts',
        'var201002': 'Number Of Unique Banks Having CASA Relationships With',
        'var201003': 'Flag - Cheque Returned',
        'var301001': 'Flag - Postpaid On Mobile',
        'var201005': 'Time Since Last Negative Event',
        'var101002': 'Flag - Salaried',
        'var201086': 'Avg. Daily Closing Balance Lifetime (Rs)',
        'var201087': 'Avg. Daily Closing Balance Last 12 Months  (Rs)',
        'var201088': 'Avg. Daily Closing Balance Last 6 Months (Rs)',
        'var201089': 'Avg. Daily Closing Balance Last 3 Months (Rs)',
        'var201090': 'Avg. Daily Closing Balance Last 1 Month (Rs)',
        'var201093': 'Monthly Average Balance Lifetime (Rs)',
        'var201094': 'Monthly Average Balance Last 12 Months  (Rs)',
        'var201095': 'Monthly Average Balance Last 6 Months (Rs)',
        'var201096': 'Monthly Average Balance Last 3 Months (Rs)',
        'var201097': 'Monthly Average Balance Last 1 Month (Rs)',
        'var201200': 'Number Of Cheques Returned Lifetime',
        'var201201': 'Number Of Cheques Returned Last 12 Months',
        'var201202': 'Number Of Cheques Returned Last 6 Months',
        'var201203': 'Number Of Cheques Returned Last 3 Months',
        'var201204': 'Number Of Cheques Returned Last 1 Month',
        'var301007': 'Avg. Monthly Recharge Amount Lifetime (Rs)',
        'var301008': 'Avg. Monthly Recharge Amount Last 12 Months (Rs)',
        'var301009': 'Avg. Monthly Recharge Amount Last 6 Months (Rs)',
        'var301010': 'Avg. Monthly Recharge Amount Last 3 Months (Rs)',
        'var301011': 'Avg. Monthly Recharge Amount Last 1 Month (Rs)',
        'var301014': 'Avg. Monthly Postpaid Bill Amount Lifetime (Rs)',
        'var301015': 'Avg. Monthly Postpaid Bill Amount Last 12 Months (Rs)',
        'var301016': 'Avg. Monthly Postpaid Bill Amount Last 6 Months  (Rs)',
        'var301017': 'Avg. Monthly Postpaid Bill Amount Last 3 Month (Rs)',
        'var601001': 'Number Of Ecom Purchases Lifetime',
        'var601002': 'Number Of Ecom Purchases Last 12 Months ',
        'var601003': 'Number Of Ecom Purchases Last 6 Months ',
        'var601004': 'Number Of Ecom Purchases Last 3 Months ',
        'var601005': 'Number Of Ecom Purchases Last 1 Month ',
        'var601006': 'Number Of Ecom Purchases Last 7 Days',
        'var601007': 'Avg Monthly Ecom Purchase Amount Life Time (Rs)',
        'var601008': 'Avg Monthly Ecom Purchase Amount Last 12 Month (Rs)',
        'var601009': 'Avg Monthly Ecom Purchase Amount Last 6 Month (Rs)',
        'var601010': 'Avg Monthly Ecom Purchase Amount Last 3 Month (Rs)',
        'var601011': 'Avg Monthly Ecom Purchase Amount Last 1 Month (Rs)',
        'var601012': 'Avg Monthly Ecom Purchase Amount Last 7 Days (Rs)',
        'var207001': 'Total Wallet Top-Up Lifetime (Rs)',
        'var207002': 'Total Wallet Top-Up Last 360 Days (Rs)',
        'var207003': 'Total Wallet Top-Up Last 180 Days (Rs)',
        'var207004': 'Total Wallet Top-Up Last 90 Days (Rs)',
        'var207005': 'Total Wallet Top-Up Last 30 Days (Rs)',
        'var207006': 'Number Of Mobile Wallets',
        'var207007': 'Number Of Wallet Top-Up Lifetime',
        'var207008': 'Number Of Wallet Top-Up Last 360 Days',
        'var207009': 'Number Of Wallet Top-Up Last 180 Days',
        'var207010': 'Number Of Wallet Top-Up Last 90 Days',
        'var207011': 'Number Of Wallet Top-Up Last 30 Days',
        'var207012': 'Number Of Total Credit Transactions',
        'var207013': 'Number Of Total Debit Transactions',
        'var207014': 'Number Of Money Transfers (Debit)',
        'var207015': 'Number Of Money Transfers (Credit)',
        'var207016': 'Amount Of Total Credit Transactions (Rs)',
        'var207017': 'Amount Of Total Debit Transactions (Rs)',
        'var207018': 'Amount Of Money Transfers (Debit) (Rs)',
        'var207019': 'Amount Of Money Transfers (Credit) (Rs)',
    },
    'Call & SMS Log Data': {
        'data_type': 'data_type',
        'status': 'status',
        'attribute': 'attribute',
        'weekday_type': 'weekday_type',
        'day_hour_type': 'day_hour_type',
        'value': 'value',
    },
}

CREDIT_REPORT_SECTION_ORDER = [
    'Loan Product',
    'Bike Loan',
    'PAN',
    'Profession',
    'Education',
    'Finance',
    'AADHAAR',
    'Salary Deviation',
    'Name Deviation',
    'DOB Deviation',
    'SMS Scraping',
    'Call & SMS Log Data',
    'Screen Event Data',
    'Field Event Data'
]

CREDIT_REPORT_SUBSECTION_ORDER = {
    'Loan Product': [
        'loan_amount',
        'loan_purpose__name',
        'monthly_income',
        'existing_emi',
    ],
    'Bike Loan': [
        'model_class',
        'brand',
        'down_payment',
        'manufacturing_year',
        'approximate_price',
    ],
    'PAN': [
        'status',
        'pan_updates',
        'first_name',
        'last_name',
        'middle_name',
        'title',
        'dob',
        'cibil_score',
        'cibil_existing_emi',
    ],
    'Profession': [
        'nature_of_work',
        'company',
        'organisation_type__name',
        'office_city',
        'upwards_prefered_partner',
        'profession_type__type_name',
        'department',
        'designation',
        'total_experience',
        'salary',
        'salary_payment_mode__name',
        'phone_no',
        'email',
        'is_phone_no_verified',
        'is_email_verified',
    ],
    'Education': [
        'qualification',
        'college',
        'completion_year',
    ],
    'Finance': [
        'any_active_loans',
        'marital_status',
        'dependents',
        'any_owned_vehicles',
        'vehicle_type',
    ],
    'AADHAAR': [
        'ekyc_applicable',
        'dob',
    ],
    'Salary Deviation': [
        'loan_specification_salary',
        'eligibility_salary',
        'sms_salary',
        'base_salary',
        'loan_specification_salary_deviation',
        'sms_salary_deviation',
    ],
    'Name Deviation': [
        'social_name',
        'pan_name',
        'aadhaar_name',
        'bank_holder_name',
        'social_pan_name_deviation',
        'pan_aadhaar_name_deviation',
        'aadhaar_bank_name_deviation',
        'bank_social_name_deviation',
    ],
    'DOB Deviation': [
        "aadhaar_pan_dob",
        "pan_dob",
        "aadhaar_dob",
    ],
    'SMS Scraping': [
        'var206002',
        'var206003',
        'var206004',
        'var206005',
        'var206006',
        'var206007',
        'var206008',
        'var206009',
        'var206010',
        'var206011',
        'var206012',
        'var206013',
        'var206020',
        'var206021',
        'var206022',
        'var206023',
        'var206024',
        'var206036',
        'var206037',
        'var101001',
        'var201001',
        'var201002',
        'var201003',
        'var301001',
        'var201005',
        'var101002',
        'var201086',
        'var201087',
        'var201088',
        'var201089',
        'var201090',
        'var201093',
        'var201094',
        'var201095',
        'var201096',
        'var201097',
        'var201200',
        'var201201',
        'var201202',
        'var201203',
        'var201204',
        'var301007',
        'var301008',
        'var301009',
        'var301010',
        'var301011',
        'var301014',
        'var301015',
        'var301016',
        'var301017',
        'var601001',
        'var601002',
        'var601003',
        'var601004',
        'var601005',
        'var601006',
        'var601007',
        'var601008',
        'var601009',
        'var601010',
        'var601011',
        'var601012',
        'var207001',
        'var207002',
        'var207003',
        'var207004',
        'var207005',
        'var207006',
        'var207007',
        'var207008',
        'var207009',
        'var207010',
        'var207011',
        'var207012',
        'var207013',
        'var207014',
        'var207015',
        'var207016',
        'var207017',
        'var207018',
        'var207019'
    ],
    'Call & SMS Log Data': [
        'Call_Incoming_Count_Week_All',
        'Call_Incoming_Count_Week_Evening',
        'Call_Incoming_Count_Week_Late Night',
        'Call_Incoming_Count_Week_Morning',
        'Call_Incoming_Count_Week_Office Hours',
        'Call_Incoming_Count_Weekday_All',
        'Call_Incoming_Count_Weekday_Evening',
        'Call_Incoming_Count_Weekday_Late Night',
        'Call_Incoming_Count_Weekday_Morning',
        'Call_Incoming_Count_Weekday_Office Hours',
        'Call_Incoming_Count_Weekend_All',
        'Call_Incoming_Count_Weekend_Evening',
        'Call_Incoming_Count_Weekend_Late Night',
        'Call_Incoming_Count_Weekend_Morning',
        'Call_Incoming_Count_Weekend_Office Hours',
        'Call_Incoming_Duration_Week_All',
        'Call_Incoming_Duration_Week_Evening',
        'Call_Incoming_Duration_Week_Late Night',
        'Call_Incoming_Duration_Week_Morning',
        'Call_Incoming_Duration_Week_Office Hours',
        'Call_Incoming_Duration_Weekday_All',
        'Call_Incoming_Duration_Weekday_Evening',
        'Call_Incoming_Duration_Weekday_Late Night',
        'Call_Incoming_Duration_Weekday_Morning',
        'Call_Incoming_Duration_Weekday_Office Hours',
        'Call_Incoming_Duration_Weekend_All',
        'Call_Incoming_Duration_Weekend_Evening',
        'Call_Incoming_Duration_Weekend_Late Night',
        'Call_Incoming_Duration_Weekend_Morning',
        'Call_Incoming_Duration_Weekend_Office Hours',
        'Call_Outgoing_Count_Week_All',
        'Call_Outgoing_Count_Week_Evening',
        'Call_Outgoing_Count_Week_Late Night',
        'Call_Outgoing_Count_Week_Morning',
        'Call_Outgoing_Count_Week_Office Hours',
        'Call_Outgoing_Count_Weekday_All',
        'Call_Outgoing_Count_Weekday_Evening',
        'Call_Outgoing_Count_Weekday_Late Night',
        'Call_Outgoing_Count_Weekday_Morning',
        'Call_Outgoing_Count_Weekday_Office Hours',
        'Call_Outgoing_Count_Weekend_All',
        'Call_Outgoing_Count_Weekend_Evening',
        'Call_Outgoing_Count_Weekend_Late Night',
        'Call_Outgoing_Count_Weekend_Morning',
        'Call_Outgoing_Count_Weekend_Office Hours',
        'Call_Outgoing_Duration_Week_All',
        'Call_Outgoing_Duration_Week_Evening',
        'Call_Outgoing_Duration_Week_Late Night',
        'Call_Outgoing_Duration_Week_Morning',
        'Call_Outgoing_Duration_Week_Office Hours',
        'Call_Outgoing_Duration_Weekday_All',
        'Call_Outgoing_Duration_Weekday_Evening',
        'Call_Outgoing_Duration_Weekday_Late Night',
        'Call_Outgoing_Duration_Weekday_Morning',
        'Call_Outgoing_Duration_Weekday_Office Hours',
        'Call_Outgoing_Duration_Weekend_All',
        'Call_Outgoing_Duration_Weekend_Evening',
        'Call_Outgoing_Duration_Weekend_Late Night',
        'Call_Outgoing_Duration_Weekend_Morning',
        'Call_Outgoing_Duration_Weekend_Office Hours',
        'Call_Outgoing/Incoming_Count Ratio_Week_All',
        'Call_Outgoing/Incoming_Count Ratio_Week_Evening',
        'Call_Outgoing/Incoming_Count Ratio_Week_Late Night',
        'Call_Outgoing/Incoming_Count Ratio_Week_Morning',
        'Call_Outgoing/Incoming_Count Ratio_Week_Office Hours',
        'Call_Outgoing/Incoming_Count Ratio_Weekday_All',
        'Call_Outgoing/Incoming_Count Ratio_Weekday_Evening',
        'Call_Outgoing/Incoming_Count Ratio_Weekday_Late Night',
        'Call_Outgoing/Incoming_Count Ratio_Weekday_Morning',
        'Call_Outgoing/Incoming_Count Ratio_Weekday_Office Hours',
        'Call_Outgoing/Incoming_Count Ratio_Weekend_All',
        'Call_Outgoing/Incoming_Count Ratio_Weekend_Evening',
        'Call_Outgoing/Incoming_Count Ratio_Weekend_Late Night',
        'Call_Outgoing/Incoming_Count Ratio_Weekend_Morning',
        'Call_Outgoing/Incoming_Count Ratio_Weekend_Office Hours',
        'Call_Outgoing/Incoming_Duration Ratio_Week_All',
        'Call_Outgoing/Incoming_Duration Ratio_Week_Evening',
        'Call_Outgoing/Incoming_Duration Ratio_Week_Late Night',
        'Call_Outgoing/Incoming_Duration Ratio_Week_Morning',
        'Call_Outgoing/Incoming_Duration Ratio_Week_Office Hours',
        'Call_Outgoing/Incoming_Duration Ratio_Weekday_All',
        'Call_Outgoing/Incoming_Duration Ratio_Weekday_Evening',
        'Call_Outgoing/Incoming_Duration Ratio_Weekday_Late Night',
        'Call_Outgoing/Incoming_Duration Ratio_Weekday_Morning',
        'Call_Outgoing/Incoming_Duration Ratio_Weekday_Office Hours',
        'Call_Outgoing/Incoming_Duration Ratio_Weekend_All',
        'Call_Outgoing/Incoming_Duration Ratio_Weekend_Evening',
        'Call_Outgoing/Incoming_Duration Ratio_Weekend_Late Night',
        'Call_Outgoing/Incoming_Duration Ratio_Weekend_Morning',
        'Call_Outgoing/Incoming_Duration Ratio_Weekend_Office Hours',
        'SMS_Incoming_Count_Week_All',
        'SMS_Incoming_Count_Week_Evening',
        'SMS_Incoming_Count_Week_Late Night',
        'SMS_Incoming_Count_Week_Morning',
        'SMS_Incoming_Count_Week_Office Hours',
        'SMS_Incoming_Count_Weekday_All',
        'SMS_Incoming_Count_Weekday_Evening',
        'SMS_Incoming_Count_Weekday_Late Night',
        'SMS_Incoming_Count_Weekday_Morning',
        'SMS_Incoming_Count_Weekday_Office Hours',
        'SMS_Incoming_Count_Weekend_All',
        'SMS_Incoming_Count_Weekend_Evening',
        'SMS_Incoming_Count_Weekend_Late Night',
        'SMS_Incoming_Count_Weekend_Morning',
        'SMS_Incoming_Count_Weekend_Office Hours',
        'SMS_Outgoing_Count_Week_All',
        'SMS_Outgoing_Count_Week_Evening',
        'SMS_Outgoing_Count_Week_Late Night',
        'SMS_Outgoing_Count_Week_Morning',
        'SMS_Outgoing_Count_Week_Office Hours',
        'SMS_Outgoing_Count_Weekday_All',
        'SMS_Outgoing_Count_Weekday_Evening',
        'SMS_Outgoing_Count_Weekday_Late Night',
        'SMS_Outgoing_Count_Weekday_Morning',
        'SMS_Outgoing_Count_Weekday_Office Hours',
        'SMS_Outgoing_Count_Weekend_All',
        'SMS_Outgoing_Count_Weekend_Evening',
        'SMS_Outgoing_Count_Weekend_Late Night',
        'SMS_Outgoing_Count_Weekend_Morning',
        'SMS_Outgoing_Count_Weekend_Office Hours',
        'SMS_Outgoing/Incoming_Count Ratio_Week_All',
        'SMS_Outgoing/Incoming_Count Ratio_Week_Evening',
        'SMS_Outgoing/Incoming_Count Ratio_Week_Late Night',
        'SMS_Outgoing/Incoming_Count Ratio_Week_Morning',
        'SMS_Outgoing/Incoming_Count Ratio_Week_Office Hours',
        'SMS_Outgoing/Incoming_Count Ratio_Weekday_All',
        'SMS_Outgoing/Incoming_Count Ratio_Weekday_Evening',
        'SMS_Outgoing/Incoming_Count Ratio_Weekday_Late Night',
        'SMS_Outgoing/Incoming_Count Ratio_Weekday_Morning',
        'SMS_Outgoing/Incoming_Count Ratio_Weekday_Office Hours',
        'SMS_Outgoing/Incoming_Count Ratio_Weekend_All',
        'SMS_Outgoing/Incoming_Count Ratio_Weekend_Evening',
        'SMS_Outgoing/Incoming_Count Ratio_Weekend_Late Night',
        'SMS_Outgoing/Incoming_Count Ratio_Weekend_Morning',
        'SMS_Outgoing/Incoming_Count Ratio_Weekend_Office Hours',
    ],
    'Screen Event Data': [
        'signup_create_session',
        'signup_create_timespent',
        'signup_update_session',
        'signup_update_timespent',
        'loan_product_create_session',
        'loan_product_create_timespent',
        'loan_product_update_session',
        'loan_product_update_timespent',
        'pan_create_session',
        'pan_create_timespent',
        'pan_update_session',
        'pan_update_timespent',
        'profession_create_session',
        'profession_create_timespent',
        'profession_update_session',
        'profession_update_timespent',
        'education_create_session',
        'education_create_timespent',
        'education_update_session',
        'education_update_timespent',
        'finance_create_session',
        'finance_create_timespent',
        'finance_update_session',
        'finance_update_timespent',
        'aadhaar_create_session',
        'aadhaar_create_timespent',
        'aadhaar_update_session',
        'aadhaar_update_timespent',
        'aadhaar_details_create_session',
        'aadhaar_details_create_timespent',
        'aadhaar_details_update_session',
        'aadhaar_details_update_timespent',
        'bank_create_session',
        'bank_create_timespent',
        'bank_update_session',
        'bank_update_timespent',
        'personal_contact_create_session',
        'personal_contact_create_timespent',
        'personal_contact_update_session',
        'personal_contact_update_timespent',
        'documents_create_session',
        'documents_create_timespent',
        'documents_update_session',
        'documents_update_timespent',
    ],
    'Field Event Data': [
        'loan_product_create_loan_purpose_edits',
        'loan_product_create_loan_purpose_deviation',
        'loan_product_create_loan_amount_edits',
        'loan_product_create_loan_amount_deviation',
        'loan_product_create_existing_emi_edits',
        'loan_product_create_existing_emi_deviation',
        'loan_product_create_loan_emi_edits',
        'loan_product_create_loan_emi_deviation',
        'loan_product_create_loan_tenure_edits',
        'loan_product_create_loan_tenure_deviation',
        'pan_create_pan_edits',
        'pan_create_pan_deviation',
        'profession_create_nature_of_work_edits',
        'profession_create_nature_of_work_deviation',
        'profession_create_company_edits',
        'profession_create_company_deviation',
        'profession_create_organisation_type_edits',
        'profession_create_organisation_type_deviation',
        'profession_create_join_date_edits',
        'profession_create_join_date_deviation',
        'profession_create_office_city_edits',
        'profession_create_office_city_deviation',
        'profession_create_profession_type_edits',
        'profession_create_profession_type_deviation',
        'profession_create_total_experience_edits',
        'profession_create_total_experience_deviation',
        'profession_create_department_edits',
        'profession_create_department_deviation',
        'profession_create_salary_edits',
        'profession_create_salary_deviation',
        'profession_create_salary_payment_mode_edits',
        'profession_create_salary_payment_mode_deviation',
        'profession_create_email_edits',
        'profession_create_email_deviation',
        'education_create_qualification_edits',
        'education_create_qualification_deviation',
        'education_create_completion_year_edits',
        'education_create_completion_year_deviation',
        'education_create_college_edits',
        'education_create_college_deviation',
        'finance_create_marital_status_edits',
        'finance_create_marital_status_deviation',
        'finance_create_any_active_loans_edits',
        'finance_create_any_active_loans_deviation',
        'finance_create_any_owned_vehicles_edits',
        'finance_create_any_owned_vehicles_deviation',
        'finance_create_dependents_edits',
        'finance_create_dependents_deviation',
        'aadhaar_create_aadhaar_edits',
        'aadhaar_create_aadhaar_deviation',
        'aadhaar_details_create_first_name_edits',
        'aadhaar_details_create_first_name_deviation',
        'aadhaar_details_create_last_name_edits',
        'aadhaar_details_create_last_name_deviation',
        'aadhaar_details_create_gender_edits',
        'aadhaar_details_create_gender_deviation',
        'aadhaar_details_create_father_first_name_edits',
        'aadhaar_details_create_father_first_name_deviation',
        'aadhaar_details_create_father_last_name_edits',
        'aadhaar_details_create_father_last_name_deviation',
        'aadhaar_details_create_mother_first_name_edits',
        'aadhaar_details_create_mother_first_name_deviation',
        'aadhaar_details_create_mother_last_name_edits',
        'aadhaar_details_create_mother_last_name_deviation',
        'aadhaar_details_create_dob_edits',
        'aadhaar_details_create_dob_deviation',
        'aadhaar_details_create_current_address_line1_edits',
        'aadhaar_details_create_current_address_line1_deviation',
        'aadhaar_details_create_current_address_line2_edits',
        'aadhaar_details_create_current_address_line2_deviation',
        'aadhaar_details_create_current_city_edits',
        'aadhaar_details_create_current_city_deviation',
        'aadhaar_details_create_current_state_edits',
        'aadhaar_details_create_current_state_deviation',
        'aadhaar_details_create_current_pincode_edits',
        'aadhaar_details_create_current_pincode_deviation',
        'aadhaar_details_create_permanent_address_line1_edits',
        'aadhaar_details_create_permanent_address_line1_deviation',
        'aadhaar_details_create_permanent_address_line2_edits',
        'aadhaar_details_create_permanent_address_line2_deviation',
        'aadhaar_details_create_permanent_city_edits',
        'aadhaar_details_create_permanent_city_deviation',
        'aadhaar_details_create_permanent_state_edits',
        'aadhaar_details_create_permanent_state_deviation',
        'aadhaar_details_create_permanent_pincode_edits',
        'aadhaar_details_create_permanent_pincode_deviation',
        'bank_create_ifsc_edits',
        'bank_create_ifsc_deviation',
        'bank_create_account_holder_name_edits',
        'bank_create_account_holder_name_deviation',
        'bank_create_account_number_edits',
        'bank_create_account_number_deviation',
        'bank_create_bank_name_edits',
        'bank_create_bank_name_deviation',
        'bank_create_branch_detail_edits',
        'bank_create_branch_detail_deviation',
        'personal_contact_create_alternate_mob_no_edits',
        'personal_contact_create_alternate_mob_no_deviation',
        'personal_contact_create_alternate_email_id_edits',
        'personal_contact_create_alternate_email_id_deviation',
        'document_create_document_type_1_edits',
        'document_create_document_type_2_edits',
        'document_create_document_type_3_edits',
        'document_create_document_type_4_edits',
        'document_create_document_type_5_edits',
        'document_create_document_type_6_edits',
        'document_create_document_type_7_edits',
        'loan_product_update_loan_purpose_edits',
        'loan_product_update_loan_purpose_deviation',
        'loan_product_update_loan_amount_edits',
        'loan_product_update_loan_amount_deviation',
        'loan_product_update_existing_emi_edits',
        'loan_product_update_existing_emi_deviation',
        'loan_product_update_loan_emi_edits',
        'loan_product_update_loan_emi_deviation',
        'loan_product_update_loan_tenure_edits',
        'loan_product_update_loan_tenure_deviation',
        'pan_update_pan_edits',
        'pan_update_pan_deviation',
        'profession_update_nature_of_work_edits',
        'profession_update_nature_of_work_deviation',
        'profession_update_company_edits',
        'profession_update_company_deviation',
        'profession_update_organisation_type_edits',
        'profession_update_organisation_type_deviation',
        'profession_update_join_date_edits',
        'profession_update_join_date_deviation',
        'profession_update_office_city_edits',
        'profession_update_office_city_deviation',
        'profession_update_profession_type_edits',
        'profession_update_profession_type_deviation',
        'profession_update_total_experience_edits',
        'profession_update_total_experience_deviation',
        'profession_update_department_edits',
        'profession_update_department_deviation',
        'profession_update_salary_edits',
        'profession_update_salary_deviation',
        'profession_update_salary_payment_mode_edits',
        'profession_update_salary_payment_mode_deviation',
        'profession_update_email_edits',
        'profession_update_email_deviation',
        'education_update_qualification_edits',
        'education_update_qualification_deviation',
        'education_update_completion_year_edits',
        'education_update_completion_year_deviation',
        'education_update_college_edits',
        'education_update_college_deviation',
        'finance_update_marital_status_edits',
        'finance_update_marital_status_deviation',
        'finance_update_any_active_loans_edits',
        'finance_update_any_active_loans_deviation',
        'finance_update_any_owned_vehicles_edits',
        'finance_update_any_owned_vehicles_deviation',
        'finance_update_dependents_edits',
        'finance_update_dependents_deviation',
        'aadhaar_update_aadhaar_edits',
        'aadhaar_update_aadhaar_deviation',
        'aadhaar_details_update_first_name_edits',
        'aadhaar_details_update_first_name_deviation',
        'aadhaar_details_update_last_name_edits',
        'aadhaar_details_update_last_name_deviation',
        'aadhaar_details_update_gender_edits',
        'aadhaar_details_update_gender_deviation',
        'aadhaar_details_update_father_first_name_edits',
        'aadhaar_details_update_father_first_name_deviation',
        'aadhaar_details_update_father_last_name_edits',
        'aadhaar_details_update_father_last_name_deviation',
        'aadhaar_details_update_mother_first_name_edits',
        'aadhaar_details_update_mother_first_name_deviation',
        'aadhaar_details_update_mother_last_name_edits',
        'aadhaar_details_update_mother_last_name_deviation',
        'aadhaar_details_update_dob_edits',
        'aadhaar_details_update_dob_deviation',
        'aadhaar_details_update_current_address_line1_edits',
        'aadhaar_details_update_current_address_line1_deviation',
        'aadhaar_details_update_current_address_line2_edits',
        'aadhaar_details_update_current_address_line2_deviation',
        'aadhaar_details_update_current_city_edits',
        'aadhaar_details_update_current_city_deviation',
        'aadhaar_details_update_current_state_edits',
        'aadhaar_details_update_current_state_deviation',
        'aadhaar_details_update_current_pincode_edits',
        'aadhaar_details_update_current_pincode_deviation',
        'aadhaar_details_update_permanent_address_line1_edits',
        'aadhaar_details_update_permanent_address_line1_deviation',
        'aadhaar_details_update_permanent_address_line2_edits',
        'aadhaar_details_update_permanent_address_line2_deviation',
        'aadhaar_details_update_permanent_city_edits',
        'aadhaar_details_update_permanent_city_deviation',
        'aadhaar_details_update_permanent_state_edits',
        'aadhaar_details_update_permanent_state_deviation',
        'aadhaar_details_update_permanent_pincode_edits',
        'aadhaar_details_update_permanent_pincode_deviation',
        'bank_update_ifsc_edits',
        'bank_update_ifsc_deviation',
        'bank_update_account_holder_name_edits',
        'bank_update_account_holder_name_deviation',
        'bank_update_account_number_edits',
        'bank_update_account_number_deviation',
        'bank_update_bank_name_edits',
        'bank_update_bank_name_deviation',
        'bank_update_branch_detail_edits',
        'bank_update_branch_detail_deviation',
        'personal_contact_update_alternate_mob_no_edits',
        'personal_contact_update_alternate_mob_no_deviation',
        'personal_contact_update_alternate_email_id_edits',
        'personal_contact_update_alternate_email_id_deviation',
        'document_update_document_type_1_edits',
        'document_update_document_type_2_edits',
        'document_update_document_type_3_edits',
        'document_update_document_type_4_edits',
        'document_update_document_type_5_edits',
        'document_update_document_type_6_edits',
        'document_update_document_type_7_edits',
    ],
}
