CREDENTIALS_FILE = 'analytics/v1/services/algo360_credentials.json'

MAB_VARIABLES = ['monthly_average_balance_lifetime', 'monthly_average_balance_12',
                 'monthly_average_balance_6', 'monthly_average_balance_3', 'monthly_average_balance_1']
SALARY_VARIABLE = 'salary'

ALGO360_UPWARDS_MAPPING = {
    'var201093': 'monthly_average_balance_lifetime',
    'var201094': 'monthly_average_balance_12',
    'var201095': 'monthly_average_balance_6',
    'var201096': 'monthly_average_balance_3',
    'var201097': 'monthly_average_balance_1',
    'var201204': 'number_of_cheque_bounce_1',
    'var201203': 'number_of_cheque_bounce_3',
    'var202003': 'is_credit_card_overlimited',
    'var202064': 'credit_card_last_payment_due',
    'var101003': 'salary',
}

CREDIT_REPORT_MAPPING = {
    'LoanProduct': {
        'fields': {
            'monthly_income': 'Monthly Income Specified on Loan Specification Screen',
            'existing_emi': 'Any Existing EMIs',
            'loan_purpose__name': 'Purpose of the Loan'
        },
        'model_class': 'loan_product.models.LoanProduct',
    },
    'BikeLoan': {
        'fields': {
            'brand': 'Brand of the Bike',
            'model_class': 'Model of the Bike',
            'manufacturing_year': 'Manufacturing year of the Bike',
            'approximate_price': 'Approximate price of the Bike',
            'down_payment': 'Down Payment of the Bike',
        },
        'model_class': 'loan_product.models.BikeLoan',
    },
    'Pan': {
        'fields': {
            'is_verified': 'Is PAN verified',
            'title': 'Title of the Customer in PAN',
            'first_name': 'First Name of the Customer in PAN',
            'middle_name': 'First Name of the Customer in PAN',
            'last_name': 'Last Name of the Customer in PAN',
            'dob': 'Date of Birth of the Customer in PAN',
            'status': 'PAN Status of the Customer',
            'pan_updates': 'PAN Updates of the Customer',
        },
        'model_class': 'pan.models.Pan',
    },
    'Profession': {
        'fields': {
            'company': 'Name of the Company, where Customer works',
            'organisation_type__name': 'Organisation type of the Company, where Customer works',
            'salary_payment_mode__name': 'Salary Payment mode of the Customer',
            'profession_type__type_name': 'Profession Type of the Customer',
            'email': 'Professional Email of the Customer',
            'is_email_verified': 'Is Professional Email of the Customer Verified?',
            'department': "Company's Department where Customer works",
            'designation': 'Designation of the Customer',
            'office_city': 'City where Customer works',
            'phone_no': 'Professional Contact number of the Customer',
            'is_phone_no_verified': 'Is Professional Contact number of the Customer Verified?',
            'salary': 'Monthly Salary of the Customer',
            'total_experience': 'Total work experience of the Customer in months',
            'nature_of_work': 'Nature of Work of the Customer',
        },
        'model_class': 'eligibility.models.Profession',
    },
    'Education': {
        'fields': {
            'college': 'Last College attended by Customer',
            'qualification': 'Highest qualification of the Customer',
            'completion_year': 'Highest qualification completion year of the Customer',
        },
        'model_class': 'eligibility.models.Education',
    },
    'Finance': {
        'fields': {
            'any_active_loans': 'Any active loans taken by the Customer',
            'any_owned_vehicles': 'Any vehicle owned by the Customer',
            'vehicle_type': 'Type of vehicle owned by the Customer',
            'marital_status': 'Maritial Status of the Customer',
            'dependents': 'Number of Dependents on Customer',
        },
        'model_class': 'eligibility.models.Finance',
    },
    'Algo360': {
        'fields':     {
            'monthly_average_balance_lifetime': 'Monthly average balance of the Customer in his lifetime',
            'monthly_average_balance_12': 'Monthly average balance of the Customer in in last 12 months',
            'monthly_average_balance_6': 'Monthly average balance of the Customer in last 6 months',
            'monthly_average_balance_3': 'Monthly average balance of the Customer in last 3 months',
            'monthly_average_balance_1': 'Monthly average balance of the Customer in last 1 months',
            'number_of_cheque_bounce_1': 'Number of cheque bounced in last month',
            'number_of_cheque_bounce_3': 'Number of cheque bounced in last 3 month',
            'salary': 'Salary deduced from SMS data',
        },
        'model_class': 'analytics.models.Algo360',
    },
}

CREDIT_REPORT_VARIABLE_NAME_MAP = {
    'Algo360': {
        'var201001': 'Number of CASA Accounts',
        'var201002': 'Number of unique banks having active CASA relationships with',
        'var201003': 'Flag - Cheque Returned',
        'var201004': 'Flag - Overdraft on CASA',
        'var201005': 'Time Since Last Negative Event (Cheque Returned, Overlimit, OD, Missed EMI)',
        'var101002': 'Flag - Salaried',
        'var201086': 'Avg. Daily Closing Balance Lifetime',
        'var201087': 'Avg. Daily Closing Balance Last 12 Months ',
        'var201088': 'Avg. Daily Closing Balance Last 6 Months',
        'var201089': 'Avg. Daily Closing Balance Last 3 Months',
        'var201090': 'Avg. Daily Closing Balance Last 1 Month',
        'var201093': 'Monthly Average Balance Lifetime',
        'var201094': 'Monthly Average Balance Last 12 Months ',
        'var201095': 'Monthly Average Balance Last 6 Months',
        'var201096': 'Monthly Average Balance Last 3 Months',
        'var201097': 'Monthly Average Balance Last 1 Month',
        'var201100': 'Maximum Balance Lifetime',
        'var201101': 'Maximum Balance Last 12 Months',
        'var201102': 'Maximum Balance Last 6 Months',
        'var201103': 'Maximum Balance Last 3 Months',
        'var201104': 'Maximum Balance Last 1 Month',
        'var201193': 'Number ECS/SI Mandates Lifetime',
        'var201194': 'Number ECS/SI Mandates Last 12 Months',
        'var201195': 'Number ECS/SI Mandates Last 6 Months',
        'var201196': 'Number ECS/SI Mandates Last 3 Months',
        'var201197': 'Number ECS/SI Mandates Last 1 Month',
        'var201200': 'Number Cheques Returned Lifetime',
        'var201201': 'Number Cheques Returned Last 12 Months',
        'var201202': 'Number Cheques Returned Last 6 Months',
        'var201203': 'Number Cheques Returned Last 3 Months',
        'var201204': 'Number Cheques Returned Last 1 Month',
        'var207006': 'Number Mobile Wallets',
        'var207001': 'Total Wallet Top-Up Lifetime',
        'var207002': 'Total Wallet Top-Up Last 360 Days',
        'var207003': 'Total Wallet Top-Up Last 180 Days',
        'var207004': 'Total Wallet Top-Up Last 90 Days',
        'var207005': 'Total Wallet Top-Up Last 30 Days',
        'var207007': 'Number Of Wallet Top-Up Lifetime',
        'var207008': 'Number Of Wallet Top-Up Last 360 Days',
        'var207009': 'Number Of Wallet Top-Up Last 180 Days',
        'var207010': 'Number Of Wallet Top-Up Last 90 Days',
        'var207011': 'Number Of Wallet Top-Up Last 30 Days',
        'var207012': 'Number Of Total Credit Transactions',
        'var207013': 'Number Of Total Debit Transactions',
        'var207014': 'Number Of Money Transfers (Debit)',
        'var207015': 'Number Of Money Transfers (Credit)',
        'var207016': 'Amount Of Total Credit Transactions',
        'var207017': 'Amount Of Total Debit Transactions',
        'var207018': 'Amount Of Money Transfers (Debit)',
        'var207019': 'Amount Of Money Transfers (Credit)',
        'var601025': 'Avg Monthly Market Place Purchase Amount Life Time',
        'var601026': 'Avg Monthly Market Place Purchase Amount Last 12 Month',
        'var601027': 'Avg Monthly Market Place Purchase Amount Last 6 Month',
        'var601028': 'Avg Monthly Market Place Purchase Amount Last 3 Month',
        'var601029': 'Avg Monthly Market Place Purchase Amount Last 1 Month',
        'var601030': 'Avg Monthly Market Place Purchase Amount Last 7 Days',
        'var601031': 'Avg Market Place Purchase Amount Per Transaction Life Time',
        'var601032': 'Avg Market Place Purchase Amount Per Transaction Last 12 Months',
        'var601033': 'Avg Market Place Purchase Amount Per Transaction Last 6 Months',
        'var601034': 'Avg Market Place Purchase Amount Per Transaction Last 3 Months',
        'var601035': 'Avg Market Place Purchase Amount Per Transaction Last 1 Month',
        'var601036': 'Avg Market Place Purchase Amount Per Transaction Last 7 Days',
    },
    'DeviceData': {
        'data_type': 'data_type',
        'status': 'status',
        'attribute': 'attribute',
        'weekday_type': 'weekday_type',
        'day_hour_type': 'day_hour_type',
        'value': 'value',
    },
}
