# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170514_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='attribute',
            field=models.CharField(choices=[('Count', 'Count'), ('Duration', 'Duration'), ('Count Ratio', 'Count Ratio'), ('Duration Ratio', 'Duration Ratio')], default='Count', max_length=50),
        ),
    ]
