# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170514_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='status',
            field=models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Missed', 'Missed'), ('Outgoing/Incoming', 'Outgoing/Incoming')], default='Incoming', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='weekday_type',
            field=models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend'), ('Week', 'Week')], default='Weekday', max_length=50),
        ),
    ]
