# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('analytics', '0004_auto_20170515_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('screen', models.CharField(choices=[('signup', 'signup'), ('loan product', 'loan product'), ('pan', 'pan'), ('profession', 'profession'), ('education', 'education'), ('financeaadhaar', 'financeaadhaar'), ('aadhaar details', 'aadhaar details'), ('bank', 'bank'), ('personal contact', 'personal contact'), ('documents', 'documents'), ('eligibility review', 'eligibility review'), ('kyc_review', 'kyc_review')], default='signup', max_length=50)),
                ('field', models.CharField(default='', max_length=100)),
                ('edits', models.IntegerField(default=1)),
                ('mode', models.CharField(choices=[('create', 'create'), ('update', 'update')], default='create', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'analytics_field_eventdata',
            },
        ),
        migrations.CreateModel(
            name='ScreenEventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_spent', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=1)),
                ('screen', models.CharField(choices=[('signup', 'signup'), ('loan product', 'loan product'), ('pan', 'pan'), ('profession', 'profession'), ('education', 'education'), ('financeaadhaar', 'financeaadhaar'), ('aadhaar details', 'aadhaar details'), ('bank', 'bank'), ('personal contact', 'personal contact'), ('documents', 'documents'), ('eligibility review', 'eligibility review'), ('kyc_review', 'kyc_review')], default='signup', max_length=50)),
                ('mode', models.CharField(choices=[('create', 'create'), ('update', 'update')], default='create', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'analytics_screen_eventdata',
            },
        ),
    ]
